### ISSUE TITLE
New function: createExposureOccurrence()

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#196]
The exposure_occurrence table is a person-centric table (a la other OMOP *_occurrence tables)

- [x] #222

Depends on
- [x] #246 should be fixed asap
> Added auto-incrementing PK as R package functionality
- [x] #241 which will change the way that joins to person_id are made
- [ ] #243 minor dependency
- [ ] #242 minor dependency for efficiency
- [x] #223 but we can hardcode fake data for now
> Fake data/ 0s for now

This issue somewhat depends on https://github.com/OHDSI/GIS/issues/240, though it is extra functionality

**Comment by kzollove** [comment]
Depends on
- [ ] #246 should be fixed asap
- [ ] #241 which will change the way that joins to person_id are made
- [ ] #243 minor dependency
- [ ] #242 minor dependency for efficiency
- [ ] #223 but we can hardcode fake data for now

**Comment by kzollove** [comment]
An MVP loadExposure() was created in 54f851b5d12ed61ca1f7bff28d7a42a1113f4189

There may be iterations, but this is enough to close this issue
