### ISSUE TITLE
Identify Datasets for testing SDoH and Exposome vocabularies

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#323]
### Project Lead:
@p-talapova 

### Tasks:

- [ ] Jimmy will attempt to map EJI variables using GIS vocabulary package and provide feedback
- [ ] #332
- [ ] Define exposure_type_concepts/ identify more useful metadata concepts, generally
- [ ] Presentation with existing hierarchy to make WG members aware of GIS vocabulary structure and begin a discussion

**Comment by kzollove** [comment]
- Polina is continuing work to update the GIS Vocabulary package
 - Goal is to publish updated version of the OHDSI GIS Vocab package and submit abstract to OHDSI symposium; due date likely late May

**Comment by p-talapova** [comment]
I would like to share the interim mapping progress on expanding and refining the GIS Vocabulary Package with respect to the selected use cases. Attached is the XLSX file with the following mappings for your review:
[GIS-vocab-package-v2-vocabulary-candidates.xlsx](https://github.com/OHDSI/GIS/files/15197972/GIS-vocab-package-v2-vocabulary-candidates.xlsx)

* **SEDH (Socioeconomic Determinants of Health)**: Involves incorporating layers that reflect economic stability, education access and quality, healthcare facility distribution, and neighborhood characteristics to enhance understanding of health disparities.
* **AQI (Air Quality Index)**: Integrates real-time and historical data on pollutants such as PM2.5, PM10, NO2, SO2, and Ozone to visualize pollution hotspots and assess health risks at a granular level.
* **EJI (Environmental Justice Index)**: Expands GIS vocab to include mapping of industrial facilities, waste disposal sites, and areas with poor air and water quality, combined with demographic data to prioritize interventions in vulnerable communities.
* **COI (Child Opportunity Index (COI)**: Focuses on assessing and mapping resources and conditions for children across neighborhoods, such as access to education, healthcare services, and recreational areas, to identify disparities and target improvements in child development and welfare.
* **ADI (Area Deprivation Index)**: Focuses on integrating socioeconomic data to highlight disadvantaged areas and aid in targeting interventions.

Please review the mappings and let me know if you have any questions or considerations.

**Comment by jaygee-on-github** [comment]
Here are some first questions i had...

For some LOINC panels like US FSS the SDOH includes all the panel members and subsume the “same” panel members in the LOINC vocabulary in ATHENA.

This, however, isn’t the pattern you follow with the GAD-7 where you only capture concepts for the panel itself in SDOH and for its score (unless I missed something).

On the other hand the PHQ-9 is a panel that ATHENA captures in the LOINC vocabulary together with its components but neither this panel nor it score nor any of its components are captured in SDOH.

These are three different treatments of LOINC panels in SDOH. How should I think about that?

This leads to whether you think it is appropriate to follow yet another pattern in SDOH. Let’s say I am using a scale for psychosis that is not a panel in LOINC. Nor is it part of any ATHENA vocabulary — standard or non-standard. Can I put this “panel” into SDOH — not just the score and the panel itself like with the GAD-7 — but all the members and structure them in SDOH just the way LOINC panel components are structured in ATHENA? Like with "contained in panel", “has answer”, “has method”, “has system” and so forth relationships?

Additionally...

Andrew suggested in the discussion following the 7/5 presentation and I agree that some additional classification besides what is in domain_id_1 (mostly "phenotypic feature") and domain_id_2 (mostly “observation") may be needed in order to better appreciate and navigate all this breadth and depth that you have created in both the SDOH and Exposome vocabularies

Thanks so much for these great vocabs, Polina.

**Comment by jaygee-on-github** [comment]
Maybe the SDoH vocabulary covers several domains, some of which are location specific and some of which are more person specific.

Recall the concept of the exposome as it was originally described by Wild and elaborated by others.

It includes the “specific external exposome” and the “general external exposome”. 

The "specific external exposome” is largely place-based and corresponds in large part to the “exposome" vocabulary that Polina and team has developed. 

The "general external exposome” corresponds in large part to the SDoH. And  the "general external exposome”, like Polina and team’s SDoH, is much more of a mixed bag.

Right now let’s recall two “views" on the external exposome. They come from different papers  and they are not altogether consistent.

Details are in the text following the image

<img width="496" alt="vocab1" src="https://github.com/user-attachments/assets/ea46c412-bdce-4653-975e-c4846a05aaed">

Here “environmental exposures” map to the specific external exposome. In the National Children’s Study (smile) we measured some pesticides, some EDCs and Cosmetics in the home. We did place-based measurements of other pesticides and EDCs.

Here the “humanistic exposure” maps to the general external exposome and it is much more of a mixed bag when it comes to measurement.

For example, here is another “view” of the external exposome:

<img width="541" alt="vocab2" src="https://github.com/user-attachments/assets/3ff73c07-5ebb-4037-8eee-ab3c859a0501">

In this view the general external exposome on the left side includes “Ecosystems” and “Ecosystems” are largely place-based. On the other hand, “Lifestyle” is person-based. And “Social” can and is measured both ways.

Recall that in the overall framework that OHDSI uses to standardize vocabularies in which Polina has hosted the two vocabularies, there are two domains: domain_id_1 is largely filled with “Phenotypic feature” and domain_id_2 is sometimes filled with “Measurement” and sometimes filled with “Observation”. Can we use one of the other or both of these domains to indicate whether a measurement in SDoH is person and/or place-based? For example we might have two rows for the same concept. In one row the measurement occurs at the person-level. In another row the same concept is measured by place. On another hand, “psychological and mental stress” are SDoHs we measure at the person-level.

It is argued that this sort of complexity can be used downstream. It creates a "multilayer network-based framework” capable of unveiling the role of exposures and their combinations on our health. Arguably, this is what neural networks were invented for.
