### ISSUE TITLE
[Roadmap]: Gaia Catalog

### ISSUE THREAD

**Issue by tibbben** [OHDSI/GIS#365]
With metadata federation and catalog interoperability as broad functionality requirements:

- [ ] define workflow for assigning concept IDs and other OHDSI vocabulary terms to catalog items
- [ ] evaluate json-ld model for cross walking data between catalogs
- [ ] develop workflow for creating attr_spec and geom_spec metadata elements

**Comment by fils** [comment]
* define workflow for assigning concept IDs and other OHDSI vocabulary terms to catalog items

Is this entity resolution?  Are these IDs in a controlled voc or ontollogy?   If so we could
look at things like entity resulution using Relik or Gliner

 * evaluate json-ld model for cross walking data between catalogs

By "cross walking between catalogs" do you mean linking?  If might that just be using PIDs and
shared instances of types to allow that to be discovered in query space?

 * incorporate metadata element for external ids for federation and sharing with other catalogs

More PIDs?   Or is this trying to assign dereferencable IRIs for resources in the catalog?

 * develop workflow for creating attr_spec and geom_spec metadata elements

Not sure what this is, need more.

 * develop tool to facilitate metadata entry

Tooling UI stuff like this is hard.   An easy entry point is trying to provide spread sheets with
drop lists (where possible) and then using that to generate the serialization.  One could try
forms too.    If there was a large set of available coding resources and the desire, one could look
at things like https://github.com/mlcommons/croissant/tree/main/editor for inspiration.

 * visual data exploration tools

Again, this is a big project.  I'd recommend looking first to things like
https://github.com/gleanerio/archetype/blob/master/docs/tooling.md#network-visualization
and generating products from OHDSI-GIS that work with those, for exploring the graph as a network.
Note, tools like Qlever also have
support for GeoSPARQL and can disply maps leveraging OpenStreet Map.  So you could graph query with
GIS connection there.

 * leverage variable and layer level concept ids for cohort definition

Out of my wheelhouse ...

 * shopping cart style data selection -> then ETL on confirmation

Shopping carts are hard too..   could you provide file serializations options as a parameter to the
the download URLs and let people collect and use those themeselves?

**Comment by fils** [comment]
Made an image for this discussion at https://github.com/fils/OHDSI-GIS-Metadata-Mapping/tree/master/docs/workflow

**Comment by jaygee-on-github** [comment]
For the JSON-LD representation in Doug's workflow we agreed to follow the EPSIFed [science-on-schema.org Dataset guide](https://github.com/ESIPFed/science-on-schema.org/blob/main/guides/Dataset.md). 

It supports describing the variables with machine understandable vocabularies. Depending on the variable type it supports other properties and their vocabularies.

**Comment by jaygee-on-github** [comment]
@kzollove , @rtmill , @fils, @tibbben, @diatomsRcool, @AEW0330 would this be a more complete way to describe dataset access in a catalog entry?

https://github.com/ESIPFed/science-on-schema.org/blob/main/guides/Dataset.md#distributions

This is another feature of the science-on-schema.org profile of a dataset that we are recommending.

When it comes to variables, following the ESIPFed profile, if the variable data type is numeric, we may want to include [schema.measurementTechnique](https://schema.org/measurementTechnique). In addition to text and a url, schema.measurementTechnique can take a [StatisticalVariable](https://schema.org/StatisticalVariable). A StatisticalVariable can capture the nuances of an observation like the ones that Charles and Lara capture in Amadeus. @kzollove it may be something we can capture downstream in the OMOP external_exposure table in your exposure_relationship_concept_id which was intended to capture "the spatiotemporal join between exposure and location in a little more detail".

**Comment by kzollove** [comment]
@jaygee-on-github As of now, there are not really any OMOP tables that attempt to capture provenance of a measurement. Would you be thinking of this information being captured in an upstream GaiaCatalog and then "translated" to a vocabulary term downstream?

There are examples from the measurement table and domain of preserving information about measurement techniques. They often rely on LOINC or CPT4 codes for standard concepts. You can see some examples in [these search results](https://athena.ohdsi.org/search-terms/terms?domain=Measurement&vocabulary=LOINC&vocabulary=CPT4&invalidReason=Valid&page=1&pageSize=15&query=estimated+glomerular).

This is sort of how I imagined an exposure_relationship_concept working. I was thinking mostly about the spatiotemporal join information like you mentioned, but I could see it (or another concept) containing measurement technique information from the source data.

**Comment by jaygee-on-github** [comment]
@kzollove, @diatomsRcool it would be great if Charles and Lara already had a vocabulary for measurement techniques. It would be for aggregates what CDEs are for observations. I think Charles had an interest in a vocabulary of StatisticalVariables for this reason. In Amadeus I think Lara has such a field but it may not be structured. StatisticalVariable can provide structured metadata for a measurement technique

**Comment by jaygee-on-github** [comment]
@kzollove @tibbben @fils @AEW0330 @diatomsRcool: Following the [science-on-schema.org Dataset profile](https://github.com/ESIPFed/science-on-schema.org/blob/main/guides/Dataset.md), Doug created a [catalog entry](https://github.com/fils/OHDSI-GIS-Metadata-Mapping/blob/master/graphs/example1.json) from a Tim GDSC catalog entry example. [This example](https://gdsc.idsc.miami.edu/solr/solr/dcat/select?fl=gdsc_attributes&indent=true&q.op=OR&q=gdsc_tablename%3Aglobal_pm25_concentration_1998_2016&wt=python) is a set of land parcels and their characteristics. The entry is a little sketchy. Also, at the variable level it includes two ways of describing a variable. In one way a variable description takes a "PropertyValue". In the other way the variable description takes a "StatisticalVariable". Each way provides a "definition of the calculated geospatial exposure metric". The "PropertyValue" path supports simple definitions. The "StatisticalVariable" path supports complex definitions. It is possible to mix and match. Doug calls this example the "0th order draft". Think of Doug's example as a template we can continue to work using Tim's example. Alternatively, we can use it as a guide which we can fill with other examples.

Tim has provided a second example from the GDSC catalog. It is a [PM2.5 example](https://gdsc.idsc.miami.edu/solr/solr/dcat/select?fl=gdsc_attributes&indent=true&q.op=OR&q=gdsc_tablename%3Aglobal_pm25_concentration_1998_2016&wt=python).

We propose to have a couple of graduate students fill in the GaiaCatalog entry "template" Doug has proposed first with the PM2.5 example and then with one or more other examples including an SDoH one.

Something that Tim covers in a GDSC catalog entry that is not supported in Doug's template at the moment is the [provenance of the dataset](https://gdsc.idsc.miami.edu/detail/mdc_parcels_camp?collection=all&active=None&query=None) that is the subject of the catalog entry. We would like to defer support for provenance in the template right now.

Additionally, we are contemplating writing a paper about the GaiaCatalog as we use it more with geospatial datasets.

**Comment by jaygee-on-github** [comment]
@fils Doug, would you agree with the following:

A variableMeasured in a science-on-schema.org Dataset can take a StatisticalVariable when it is an aggregate. Alternatively, an aggregate can take a PropertyValue just like an observation or measurement does.

[The Croissant Dataset profile](https://docs.mlcommons.org/croissant/docs/croissant-spec.html) is an alternative to the science-on-schema.org Dataset profile when the datapoints in a Dataset are not aggregates. Recall that in the Croissant profile a Dataset distribution takes a cr:FileObject or a cr:FileSet, and a cr:FileObject can be the source of cr:RecordSet which contains one or more cr:Field. Arguably a cr:Field in Croissant does not host aggregates like a variable in the science-on-schema.org Dataset profile can.

**Comment by tibbben** [comment]
Perhaps useful as examples:  

the GDSC catalog on Box (for this focus on the "attributes" and "table_name" columns):  
https://miami.box.com/s/cpe136whxprafac9ssvkig74ju4o2x7m

The SOLR endpoint (global pm 2.5 as a fairly complete example):  
```
https://gdsc.idsc.miami.edu/solr/solr/dcat/select?fl=gdsc_attributes&indent=true&q.op=OR&q=gdsc_tablename%3Aglobal_pm25_concentration_1998_2016&wt=python
```

_note:_ the gdsc_tablename can be edited with any table_name from the box file, for example the following is for table name "fl_2020_svi_county" (a less complete example):
```
https://gdsc.idsc.miami.edu/solr/solr/dcat/select?fl=gdsc_attributes&indent=true&q.op=OR&q=gdsc_tablename%3Afl_2020_svi_county&wt=python
```

And you can explore the metadata and some of the geographies at:
https://gdsc.idsc.miami.edu/detail/global_pm25_concentration_1998_2016?collection=all&active=None&query=pm2.5

**Comment by jaygee-on-github** [comment]
Using Tim's examples, this week we launched an activity staffed by a couple of [APHRC](https://aphrc.org) graduate students that will use the template Doug developed. Recall it is based on the science-on-schema.org Dataset profile. However, the GDSC and other catalogs support provenance. With this in mind in a future we will be considering another Dataset profile Doug has contributed to: Croissant. We are also mindful of the RO-Crate work that Kyle is exploring.
