### ISSUE TITLE
[Roadmap] Geocoding

### ISSUE THREAD

**Issue by jphuong** [OHDSI/GIS#366]
1. Development geocoding goals

2. Defining spatial level of deployment (Regional, US-centric, International, Continental)
- US-centric geocoding requirements
- International geocoding requirements

3. Definition of readiness
- Unit testing and build testing procedures
- sample dataset 
- benchmarking 

4. Vocabulary extension for geocoding attributes
 - Documentation and guidance on the metadata strategies
 - Attribution of geocoding method (e.g., interpolated or parcel-based methods) and quality metrics
 
5. Containerized deployments for geocoding
 - Postgis
 - DeGauss
 - Nominatim

**Comment by tdrossi** [comment]
I want to echo Cindy's comments, especially the potential importance of geocoding relative to unlocking environmental health regarding exposomics and SDoH. As I’m still learning about the scope of the OHDSI GIS group, I would also like to inquire about a few other topics in this realm:
 
-  Regarding Cindy's comment on international standards of “street, number, city, postal code”, can there be an equivalent geolocation measurement used for places and buildings to avoid issues of confusion related to addresses? In particular, creating a digital "polygon" geometry representing the building's boundaries, which can then be correlated to BIM (Building Information Management), can provide accurate measurements regarding IEQ (Indoor Environmental Quality). IEQ includes air quality, lighting, acoustics, thermal comfort, and other environmental factors, not just IAQ (i.e., PM 2.5).
 
-  I’m wondering about the ERD of elevation data fields to denote building floors/levels to ensure building location measurements that can be included with data recorded as environmental exposures. This can ensure an option of a delta between exterior and interior environmental measurements on a more granular level (if possible). Would this be a simple geom x,y,z field that is utilized?
 
-  If this exposure data is included in an EHR as a Comprehensive Health Record (CHR), what field mapping is planned from an informatics perspective relative to SNOMED, LOINC, etc.? There are some SNOMED and LOINC codes relating to the environment and the built environment. Is there an outline of these fields that this group has outlined? Agree with Cindy that this type of measurement can be bridged by a spatial join.

- I am also curious if any fields specify whether these measurements are outside or inside a built environment.

**Comment by jphuong** [comment]
Hi folks - 

I'm addressing the feedback above together to make final draft changes in the order and wording of the geocoding roadmap.
 
- The benchmarking test included in the 2024 symposium presentation is very helpful. Do we have plans to expand this to an international setting first before deciding on what to include for the OHDSI GIS WG? For example, I see there is a step to prepare address strings for geocoding, do we know if “street, number, city, postal code” are applicable to other countries? We talked about reaching out to the collaborator from Brazil during the 12/6 meeting

> These are good points. We know that geocoding is no longer going to be part of the Gaia containerized deployment, so we may need to consider the architectural and upstream and downstream data flow leading into a geocoding container deployment. 
- [ ] draft an architectural diagram and entity-relationship diagram for the data flow leading to and out of the geocoding container deployment

> Multiple geocoders and configurations are available. I see the the US-centric and the International/Regional geocoding as separate data input requirements (e.g., Postal address line) to consider. And, once that is chosen, there are system unit tests to establish that the geocoding container is indeed operation. The sample dataset and benchmarking for geocoding performance would make sense after the US or International/Regional setting is chosen. So, I will revise to the following:

- [ ] draft the geocoding scenario within the US or International/Regional areas, the open source geocoding containers and premium software options for this choice, then identify the inputs and outputs expected
- [ ] establish sample dataset requirements for unit test and test geocoding runs
- [ ] consider approaches to iterate on the benchmarking for geocoding performance (e.g., speed, quality, limitations)

- I want to stress the potential importance of geocoding if it were to be deployed successfully. For example, the All of Us program adopts OMOP CDM but currently address are not geocoded. Making this available would have huge impacts on unlocking environmental health research in All of Us.

> This is a good point. We have a few slide decks to discuss the WG work. Geocoding containerized deployments may have a value proposition for institutions and currently funded projects that have adopted OMOP CDM. Identifying venues to showcase these tools could be of interest.

- [ ] identify venues for showcasing geocoding workflow

- As for maintaining the data catalog, I think it is going to be a huge burden to maintain this as the source data keeps changing. If you only include select numbers of indicators then there will always be someone who asks “how about XYZ”, if you include as many as you can up keeping can be a huge burden and it will also be quite overwhelming for users to access. I guess my suggestion is to leave it up to the individual investigators. OHDSI provides the geocoding tool, what investigators want to do with the lat/long is up to them. They can bring in user-defined layers of environmental exposure or social determinants of health data, and perform a spatial join.

> This sounds more like connecting the geocoding outputs to the data catalog and External Exposure table relationships. The user-defined layers may belong in the Data Catalog roadmap. I will add in to "consider user-centered workflows and documentation for integrating geocoding outputs with the data catalog." This may make sense as a decision point while choosing the scale of geocoding (US versus International/Regional).

- [ ] consider user-centered workflows and documentation for integrating geocoding outputs, the output resolution, with the data catalog

- Regarding Cindy's comment on international standards of “street, number, city, postal code”, can there be an equivalent geolocation measurement used for places and buildings to avoid issues of confusion related to addresses? In particular, creating a digital "polygon" geometry representing the building's boundaries, which can then be correlated to BIM (Building Information Management), can provide accurate measurements regarding IEQ (Indoor Environmental Quality). IEQ includes air quality, lighting, acoustics, thermal comfort, and other environmental factors, not just IAQ (i.e., PM 2.5).

I’m wondering about the ERD of elevation data fields to denote building floors/levels to ensure building location measurements that can be included with data recorded as environmental exposures. This can ensure an option of a delta between exterior and interior environmental measurements on a more granular level (if possible). Would this be a simple geom x,y,z field that is utilized?

> All geocoding has a degree of uncertainty and error that sometimes cannot link with a single building. Perhaps, only parcel-based geocoding may allow for this, but the building elevation knowledge may add more complexity. Some Interpolated geocoding can also be applied for translating "intersections", such that the geocoding is not limited to building addresses.

- [ ] consider linkage with built environmental factors and neighborhood quality and measurements

If this exposure data is included in an EHR as a Comprehensive Health Record (CHR), what field mapping is planned from an informatics perspective relative to SNOMED, LOINC, etc.? There are some SNOMED and LOINC codes relating to the environment and the built environment. Is there an outline of these fields that this group has created? Agree with Cindy that this type of measurement can be bridged by a spatial join.

I am also curious if any fields specify whether these measurements are outside or inside a built environment.

> I think these vocabulary developments and considerations belong in the Vocabulary Roadmap. There's perhaps the process to initiate nomination and review for new vocabulary domains

- [ ] explore process for initiating nomination, review, and test application with vocabulary for representing Indoor Environmental Quality

> I will incorporate these bullets to update the geocoding roadmap above

**Comment by jphuong** [comment]
@p-talapova see the comment about the Built environment data and vocabularies from @tdrossi
