### ISSUE TITLE
[Roadmap] Gaia

### ISSUE THREAD

**Issue by rtmill** [OHDSI/GIS#368]
[working] 
Create stable release of Gaia that is tested, documented and versioned. To that end, we have a list of outstanding questions and gaps to be addressed that we be binned into either necessary for the stable release or to be addressed afterwards. 

- [ ] Address outstanding questions. Determine if needed before or after stable release. Create bins, define work and create tickets
  - [ ] Determine, strictly, the functional scope of Gaia and what is outside of it
  - [ ] Settle on approach for '_spec' (move away from R)
  - [ ] Derivation provenance 
    - [ ] geom to person 
    - [ ] geocoding method
  - [ ] Distribution strategies for:
    - [ ] GaiaCore 
    - [ ] GaiaDB
    - [ ] Discuss Single source DDL
  - [ ] Vocabulary integration strategy
  - [ ] Data source management
    - [ ] Accounting for changes to data sources
    - [ ] Unique identification of data sources ( approach for minting new IDs asynchronously)  
- [ ] Stable release of Gaia
  - [ ] Separate into distinct repos  
  - [ ] GaiaCore 
  - [ ] GaiaDB
  - [ ] Adequate documentation
- [ ] Sufficiently triage work determined to be out of scope for stable release into future development work (make tickets for future work)

**Comment by AEW0330** [comment]
Thanks for doing this roadmap. 

The need for relatively complete documentation is urgent. 

Can we get you help from the CHIRON cohort or elsewhere to do this soon? I think buy in for further development could be delayed if more adequate documentation waits until the prior issues re refactoring, etc. are resolved. 

Work on the documentation for the current approach also seems like it could also help clarify the thinking about new options.
